# Generated by Django 4.0 on 2022-01-09 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='totalHours',
            field=models.DurationField(default=datetime.time(1, 0)),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(),
        ),
    ]
